# Generated by Django 4.2.3 on 2023-07-09 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BranchModel",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("org_code", models.CharField(max_length=5)),
                (
                    "org_name",
                    models.CharField(
                        db_column="org_name", db_index=True, max_length=250
                    ),
                ),
                (
                    "nick_name",
                    models.CharField(
                        db_column="nick_name", db_index=True, max_length=20
                    ),
                ),
                (
                    "registration_date",
                    models.DateField(
                        blank=True, db_column="registration_date", null=True
                    ),
                ),
                (
                    "registration_number",
                    models.CharField(
                        blank=True, db_column="registration_number", null=True
                    ),
                ),
                (
                    "pan_number",
                    models.CharField(blank=True, db_column="pan_number", null=True),
                ),
                (
                    "country",
                    models.CharField(blank=True, db_column="country", null=True),
                ),
                (
                    "province",
                    models.CharField(blank=True, db_column="province", null=True),
                ),
                (
                    "district",
                    models.CharField(blank=True, db_column="district", null=True),
                ),
                ("street", models.CharField(blank=True, db_column="street", null=True)),
                (
                    "contact_number",
                    models.CharField(blank=True, db_column="contact_number", null=True),
                ),
                (
                    "web_address",
                    models.CharField(blank=True, db_column="web_address", null=True),
                ),
                ("fax", models.CharField(blank=True, db_column="fax", null=True)),
                (
                    "is_primary_office",
                    models.BooleanField(db_column="is_primary_office"),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "creator",
                    models.ForeignKey(
                        db_column="creator",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": 'core"."branches',
            },
        ),
    ]
