# Generated by Django 4.2.3 on 2023-07-10 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MenuModel",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("menu_code", models.CharField(max_length=6)),
                ("menu_name", models.CharField(max_length=20)),
                ("url", models.CharField(max_length=100)),
                (
                    "menu_type",
                    models.CharField(
                        choices=[("H", "Main"), ("M", "Sub Menu"), ("R", "Report")]
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "parent_id",
                    models.ForeignKey(
                        db_column="parent_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="core.menumodel",
                    ),
                ),
            ],
            options={
                "db_table": 'core"."menus',
            },
        ),
    ]
