# Generated by Django 4.2.3 on 2023-07-10 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_menumodel_parent_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="DistrictModel",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("district_name", models.CharField()),
                ("district_name_np", models.CharField()),
            ],
            options={
                "db_table": 'core"."districts',
            },
        ),
        migrations.CreateModel(
            name="ProvincesModel",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("province_name", models.CharField()),
                ("province_name_np", models.CharField()),
            ],
            options={
                "db_table": 'core"."provinces',
            },
        ),
        migrations.CreateModel(
            name="LocalBodiesModel",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("local_body_name", models.CharField()),
                ("local_body_name_np", models.CharField()),
                (
                    "local_body_type",
                    models.CharField(
                        choices=[
                            ("Municipality", "Municipality"),
                            ("Rural Municipality", "Rural Municipality"),
                            ("Metropolitian City", "Metropolitian City"),
                            ("Sub-Metropolitian City", "Sub-Metropolitian City"),
                        ]
                    ),
                ),
                (
                    "district_id",
                    models.ForeignKey(
                        db_column="district_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="core.districtmodel",
                    ),
                ),
            ],
            options={
                "db_table": 'core"."local_bodies',
            },
        ),
        migrations.AddField(
            model_name="districtmodel",
            name="province_id",
            field=models.ForeignKey(
                db_column="province_id",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="core.provincesmodel",
            ),
        ),
    ]
