# Generated by Django 4.2.3 on 2023-07-12 07:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0004_districtmodel_provincesmodel_localbodiesmodel_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AcademicYearModel",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("ac_year_code", models.CharField(max_length=20)),
                ("ac_year_name", models.CharField(max_length=20)),
                ("starts_on", models.DateField()),
                ("ends_on", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        db_column="created_by",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": 'core"."academic_year',
            },
        ),
    ]
