# Generated by Django 4.2.3 on 2023-07-29 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_academicyearmodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="NepaliDateModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year_id", models.IntegerField(db_column="year_id")),
                ("month_id", models.IntegerField(db_column="month_id")),
                ("day_id", models.IntegerField(db_column="day_id")),
                ("start_date", models.DateField(db_column="start_date")),
                ("end_date", models.DateField(db_column="end_date")),
            ],
            options={
                "verbose_name": "Nepali Date",
                "verbose_name_plural": "Nepali Dates",
                "db_table": 'core"."nepali_dates',
            },
        ),
    ]
