# Generated by Django 4.2.3 on 2023-07-30 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0006_nepalidatemodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="DayOperationsModel",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("value_date", models.DateField()),
                ("is_completed", models.BooleanField(default=False)),
                ("eod_on", models.DateTimeField()),
                (
                    "eod_by",
                    models.ForeignKey(
                        db_column="eod_by",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Day Operation",
                "verbose_name_plural": "Day Operations",
                "db_table": 'core"."day_operation',
            },
        ),
    ]
