# Generated by Django 4.2.3 on 2023-08-08 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_dayoperationsmodel_eod_on"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttachmentModel",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("table_name", models.CharField(max_length=50)),
                ("table_id", models.BigIntegerField()),
                ("attachment_type", models.CharField(max_length=10)),
                ("original_file_name", models.CharField(max_length=100)),
                ("file_name", models.CharField(max_length=500)),
                ("is_active", models.BooleanField(default=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Attachment",
                "verbose_name_plural": "Attachments",
                "db_table": 'core"."attachments',
            },
        ),
    ]
