# Generated by Django 4.2.3 on 2023-08-09 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_attachmentmodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attachmentmodel",
            name="attachment_type",
            field=models.CharField(max_length=50),
        ),
    ]
