# Generated by Django 4.2.3 on 2023-11-02 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_alter_attachmentmodel_attachment_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="menumodel",
            options={"ordering": ["menu_code"]},
        ),
        migrations.AddField(
            model_name="menumodel",
            name="hidden",
            field=models.BooleanField(db_column="hidden", default=False),
        ),
        migrations.AlterField(
            model_name="menumodel",
            name="menu_type",
            field=models.CharField(
                choices=[("H", "Head"), ("M", "Sub Menu"), ("R", "Report")]
            ),
        ),
        migrations.AlterField(
            model_name="menumodel",
            name="parent_id",
            field=models.ForeignKey(
                blank=True,
                db_column="parent_id",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="core.menumodel",
            ),
        ),
    ]
