# Generated by Django 4.2.3 on 2023-07-14 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0005_academicyearmodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="DepartmentModel",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("department_name", models.CharField(max_length=50)),
            ],
            options={
                "db_table": 'staff"."departments',
            },
        ),
        migrations.CreateModel(
            name="StaffDesignationModel",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("designation_name", models.CharField(max_length=50)),
                (
                    "department_id",
                    models.ForeignKey(
                        db_column="department_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="staff.departmentmodel",
                    ),
                ),
            ],
            options={
                "db_table": 'staff"."staff_designations',
            },
        ),
        migrations.CreateModel(
            name="StaffModel",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("staff_name", models.CharField(max_length=100)),
                ("staff_address", models.CharField(max_length=100)),
                ("staff_contact", models.CharField(max_length=15)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Other", "Other"),
                            ("RatherNotSay", "Rather Not Say"),
                        ]
                    ),
                ),
                (
                    "maritial_status",
                    models.CharField(
                        choices=[
                            ("Married", "Married"),
                            ("UnMarried", "Un Married"),
                            ("Divorced", "Divorced"),
                            ("Seperated", "Seperated"),
                        ]
                    ),
                ),
                ("joined_date", models.DateField()),
                ("resigned_on", models.DateField(null=True)),
                (
                    "branch_id",
                    models.ForeignKey(
                        db_column="branch_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="core.branchmodel",
                    ),
                ),
                (
                    "designation_id",
                    models.ForeignKey(
                        db_column="designation_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="staff.staffdesignationmodel",
                    ),
                ),
            ],
            options={
                "db_table": 'staff"."staff_details',
            },
        ),
    ]
