# Generated by Django 4.2.3 on 2023-07-15 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0004_alter_coursesmodel_course_code_and_more"),
        ("staff", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffmodel",
            name="assigned_subject",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="academic.subjectmodel",
            ),
        ),
        migrations.AlterField(
            model_name="staffmodel",
            name="maritial_status",
            field=models.CharField(
                choices=[
                    ("Married", "Married"),
                    ("Single", "Single"),
                    ("Divorced", "Divorced"),
                    ("Seperated", "Seperated"),
                ]
            ),
        ),
    ]
