# Generated by Django 4.2.3 on 2023-07-23 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0002_staffmodel_assigned_subject_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="departmentmodel",
            options={"verbose_name": "Deparment", "verbose_name_plural": "Deparments"},
        ),
        migrations.AlterModelOptions(
            name="staffdesignationmodel",
            options={
                "verbose_name": "Designation",
                "verbose_name_plural": "Designations",
            },
        ),
        migrations.AlterModelOptions(
            name="staffmodel",
            options={"verbose_name": "Staff", "verbose_name_plural": "Staffs"},
        ),
    ]
