# Generated by Django 4.2.3 on 2023-08-18 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0009_alter_academicchargesmodel_charge_amount'),
        ('student', '0011_studentclassmodel_academic_session_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionMasterModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tran_date', models.DateField()),
                ('verification_id', models.IntegerField(choices=[(1, 'Verified'), (-1, 'Rejected'), (0, 'Unverified'), (2, 'AutoVerified')])),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('verified_on', models.DateField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_by', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='verified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction Master',
                'verbose_name_plural': 'Transaction Masters',
                'db_table': 'tran"."transaction_master',
            },
        ),
        migrations.CreateModel(
            name='AdmissionTransactionModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tran_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('statement_reference', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('charge_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='academic.academicchargesmodel')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='student.studentmodel')),
                ('tran_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tran.transactionmastermodel')),
            ],
            options={
                'verbose_name': 'Admission Transaction',
                'verbose_name_plural': 'Admission Transactions',
                'db_table': 'tran"."admission_transactions',
            },
        ),
    ]
