# Generated by Django 4.2.3 on 2023-08-20 06:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tran', '0003_transactionmastermodel_tran_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionmastermodel',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
