# Generated by Django 4.2.3 on 2023-08-20 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tran', '0004_alter_transactionmastermodel_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionmastermodel',
            name='verified_on',
            field=models.DateField(null=True),
        ),
    ]
