# Generated by Django 4.2.3 on 2023-08-21 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tran', '0005_alter_transactionmastermodel_verified_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempTranCode',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=6)),
                ('tran_count', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Temp Tran Code',
                'verbose_name_plural': 'Temp Tran Codes',
                'db_table': 'tran"."temp_tran_code',
            },
        ),
    ]
