# Generated by Django 4.2.3 on 2023-11-02 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tran", "0006_temptrancode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admissiontransactionmodel",
            name="tran_id",
            field=models.ForeignKey(
                db_column="tran_id",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="tran_id",
                to="tran.transactionmastermodel",
            ),
        ),
    ]
