# Generated by Django 4.2.3 on 2023-07-12 07:44

from django.db import migrations

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubjectModel",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("subject_code", models.CharField(max_length=6)),
                ("subject_name", models.CharField(max_length=60)),
                ("status", models.BooleanField(default=True)),
            ],
             options={
                "db_table": 'academic"."subjects',
            },
        )    
        ]

