# Generated by Django 4.2.3 on 2023-07-12 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0003_alter_academicclassmodel_class_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursesmodel",
            name="course_code",
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name="coursesmodel",
            name="course_name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
