# Generated by Django 4.2.3 on 2023-07-23 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0004_alter_coursesmodel_course_code_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="academicclassmodel",
            options={"verbose_name": "Class", "verbose_name_plural": "Classes"},
        ),
        migrations.AlterModelOptions(
            name="academicsectionmodel",
            options={"verbose_name": "Section", "verbose_name_plural": "Sections"},
        ),
        migrations.AlterModelOptions(
            name="academictypemodel",
            options={
                "verbose_name": "Academic Type",
                "verbose_name_plural": "Academic Types",
            },
        ),
        migrations.AlterModelOptions(
            name="coursesmodel",
            options={"verbose_name": "Course", "verbose_name_plural": "Courses"},
        ),
        migrations.AlterModelOptions(
            name="subjectmodel",
            options={"verbose_name": "Subject", "verbose_name_plural": "Subjects"},
        ),
    ]
