# Generated by Django 4.2.3 on 2023-08-16 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0007_academicchargesmodel_academic_session_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicchargesmodel',
            name='academic_session_type',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
