# Generated by Django 4.2.3 on 2023-08-16 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0008_alter_academicchargesmodel_academic_session_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicchargesmodel',
            name='charge_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
