# Generated by Django 4.2.3 on 2023-07-23 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_academicyearmodel"),
        ("authentication", "0003_remove_user_is_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="branch_id",
            field=models.ForeignKey(
                db_column="branch_id",
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="core.branchmodel",
            ),
            preserve_default=False,
        ),
    ]
