import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Providers } from './providers'
import Layout from '@/components/Layout'
import { headers } from 'next/headers';
import React from 'react'
import AuthChecker from '@/components/Auth/AuthChecker'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'School Mananagement System',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  // const headersList = headers();
  // const domain = headersList.get('host') || "";
  // const fullUrl = headersList.get('referer') || "";
  // const [, pathname] = fullUrl.match(new RegExp(`https?:\/\/${domain}(.*)`)) || [];

  // const LayoutNotNeeded = ['/auth/login', 'auth/signup'].includes(pathname);

  // const LayoutComponent = LayoutNotNeeded ?  React.Fragment : Layout ;



  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <AuthChecker>
            {children}
          </AuthChecker>
        </Providers>
      </body>
    </html >
  )
}
