import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Providers } from './providers'
import React  from 'react'
import AuthChecker from '@/components/Auth/AuthChecker'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'School Mananagement System',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <AuthChecker>
            {children}
          </AuthChecker>
        </Providers>
      </body>
    </html >
  )
}
