# Generated by Django 4.2.3 on 2023-07-12 07:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_academicyearmodel"),
        ("academic", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("student", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentClassModel",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("admission_date", models.DateField()),
                ("has_passed", models.BooleanField(default=False)),
                ("passed_year", models.DateField(blank=True, null=True)),
                ("passed_grade", models.CharField(blank=True, null=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="core.academicyearmodel",
                    ),
                ),
                (
                    "class_id",
                    models.ForeignKey(
                        db_column="class_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="academic.academicclassmodel",
                    ),
                ),
                (
                    "course_id",
                    models.ForeignKey(
                        blank=True,
                        db_column="course_id",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="academic.coursesmodel",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        db_column="created_by",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "falculty_id",
                    models.ForeignKey(
                        blank=True,
                        db_column="falculty_id",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="academic.facultymodel",
                    ),
                ),
                (
                    "student_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="student.studentmodel",
                    ),
                ),
            ],
            options={
                "db_table": 'student"."class_details',
            },
        ),
    ]
