# Generated by Django 4.2.3 on 2023-07-13 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0004_alter_coursesmodel_course_code_and_more"),
        ("student", "0002_studentclassmodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentclassmodel",
            name="academic_year",
            field=models.ForeignKey(
                db_column="academic_year_id",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="core.academicyearmodel",
            ),
        ),
        migrations.RenameField(
            model_name="studentclassmodel",
            old_name="academic_year",
            new_name="academic_year_id",
        ),
        migrations.RemoveField(
            model_name="studentclassmodel",
            name="falculty_id",
        ),
        migrations.AddField(
            model_name="studentclassmodel",
            name="faculty_id",
            field=models.ForeignKey(
                blank=True,
                db_column="faculty_id",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="academic.facultymodel",
            ),
        ),
        migrations.AlterField(
            model_name="studentclassmodel",
            name="student_id",
            field=models.ForeignKey(
                db_column="student_id",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="student.studentmodel",
            ),
        ),
    ]
