# Generated by Django 4.2.3 on 2023-07-14 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0005_studentaddressmodel_student_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentmodel",
            name="gender",
            field=models.CharField(
                choices=[
                    ("Male", "Male"),
                    ("Female", "Female"),
                    ("Other", "Other"),
                    ("RatherNotSay", "Rather Not Say"),
                ],
                default="Male",
            ),
            preserve_default=False,
        ),
    ]
