# Generated by Django 4.2.3 on 2023-07-28 18:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0006_studentmodel_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentmodel",
            name="introduced_on",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 7, 28, 18, 25, 54, 781415, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="studentmodel",
            name="student_id",
            field=models.BigIntegerField(
                db_column="student_id", default=1, unique=True
            ),
            preserve_default=False,
        ),
    ]
