# Generated by Django 4.2.3 on 2023-07-30 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0006_nepalidatemodel"),
        ("student", "0007_studentmodel_introduced_on_studentmodel_student_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentaddressmodel",
            name="district_id",
            field=models.ForeignKey(
                db_column="district_id",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="core.districtmodel",
            ),
        ),
        migrations.AlterField(
            model_name="studentaddressmodel",
            name="state_id",
            field=models.ForeignKey(
                db_column="state_id",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="core.provincesmodel",
            ),
        ),
        migrations.AlterField(
            model_name="studentaddressmodel",
            name="ward_no",
            field=models.IntegerField(db_column="local_bodies_id"),
        ),
        migrations.AlterField(
            model_name="studentcontactmodel",
            name="relation_type",
            field=models.CharField(
                choices=[
                    ("Father", "Father"),
                    ("Mother", "Mother"),
                    ("Other", "Other"),
                    ("Self", "Self"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="studentmodel",
            name="created_by",
            field=models.ForeignKey(
                db_column="created_by",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
