# Generated by Django 4.2.3 on 2023-08-18 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_studentadmissionviewmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentclassmodel',
            name='faculty_id',
        ),
    ]
