# Generated by Django 4.2.3 on 2023-08-18 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_remove_studentclassmodel_faculty_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentclassmodel',
            name='academic_session_type',
            field=models.IntegerField(blank=True, db_column='academic_session_type', null=True),
        ),
    ]
