# Generated by Django 4.2.3 on 2023-08-21 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tran', '0006_temptrancode'),
        ('student', '0011_studentclassmodel_academic_session_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentclassmodel',
            name='tran_id',
            field=models.ForeignKey(db_column='tran_id', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='tran.transactionmastermodel'),
            preserve_default=False,
        ),
    ]
