# Generated by Django 4.2.3 on 2023-08-23 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_studentclassmodel_tran_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentaddressmodel',
            name='ward_no',
            field=models.IntegerField(db_column='ward_no'),
        ),
    ]
