# Generated by Django 4.2.3 on 2023-08-23 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_attachmentmodel_attachment_type'),
        ('student', '0013_alter_studentaddressmodel_ward_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentaddressmodel',
            name='local_bodies_id',
            field=models.ForeignKey(db_column='local_bodies_id', on_delete=django.db.models.deletion.DO_NOTHING, to='core.localbodiesmodel'),
        ),
    ]
